name: test aeson
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test-aeson:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build Test
        run: echo "TEST_IMAGE=$(docker build --target test --quiet ./aeson)" >> $GITHUB_ENV
      # - name: Run Test
      #   run: docker run $TEST_IMAGE
