name: test core
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test-core:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build Test
        run: echo "TEST_IMAGE=$(docker build --target test --quiet ./core)" >> $GITHUB_ENV
      - name: Run Test
        run: docker run $TEST_IMAGE
