name: test core
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test-core:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create action id
        run: echo "ACTION_ID=${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
      - name: Build Test
        run: docker build --target test --tag $ACTION_ID ./core
      - name: Run Test
        run: docker run $ACTION_ID
