# See: https://github.com/marketplace/actions/run-hlint
# See: https://github.com/marketplace/actions/ormolu-action

name: lint
on:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: Lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hlint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up HLint
        uses: rwe/actions-hlint-setup@v1
        with:
          version: '3.1.6'

      - name: Run HLint
        uses: rwe/actions-hlint-run@v2
        with:
          path: '["core/src/", "core/test/", "aeson/src/"]'
          fail-on: suggestion
  ormolu:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Ormolu
        uses: mrkkrp/ormolu-action@v4
  ghc:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create action id
        run: echo "ACTION_ID=${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
      - name: Build Error Image
        run: docker build --force-rm --tag $ACTION_ID -f Docker/Dockerfile.error .
      - name: Run Error Image
        run: docker run --rm $ACTION_ID
      - name: Remove Test Image
        run: docker image rm --no-prune $ACTION_ID
        if: always()
