name: test
on:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: Test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create action id
        run: echo "ACTION_ID=${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
      - name: Build Test Image
        run: docker build --tag $ACTION_ID -f Dockerfile.test .
      - name: Run Test Image
        run: docker run --rm $ACTION_ID
      - name: Remove Test Image
        run: docker image rm $ACTION_ID
        if: always()
  doctest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create action id
        run: echo "ACTION_ID=${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
      - name: Build Doctest Image
        run: docker build --tag $ACTION_ID -f Dockerfile.doctest .
      - name: Run Doctest Image
        run: docker run --rm $ACTION_ID
      - name: Remove Doctest Image
        run: docker image rm $ACTION_ID
        if: always()
